# Laboratorio 0

Librerias



In [1]:
import numpy as np

# Punto 1



Nos basamos en la solución de [numpy matrix vector multiplication](https://stackoverflow.com/questions/21562986/numpy-matrix-vector-multiplication) y en la documentación de [How to raise a numpy array to a power?](https://stackoverflow.com/questions/5018552/how-to-raise-a-numpy-array-to-a-power-corresponding-to-repeated-matrix-multipl)

a) y b) : La función $f$ que satisface los requerimientos de a) y b) es $\texttt{fun1(A,B,c,d)}$.

Esta función maneja dos tipos de errores. El primero cuando $\texttt{A}$ tiene mas columnas que $\texttt{B}$ filas y el segundo, cuando sucede lo contrario.

In [2]:
def fun1(A, B, c = 1, d = 1):
    
    # Transformar los objetos en arreglos tipo numpy
    A = np.array(A)
    B = np.array(B)
    
    # Primer tipo de error de dimensión
    if A.shape[1] > B.shape[0]:
        out = 'Error: El primer arreglo tiene mas columnas que el segundo filas'
    # Segundo tipo de error de dimensión
    elif A.shape[1] < B.shape[0]:
        out = 'Error: El primer arreglo tiene menos columnas que el segundo filas'
    # Realiza la operación
    else:
        # linalg.matrix_power genera error para matrices no cuadradas
        #                     independientemente de que el exponente sea 1
        #           Manejamos el error
        if c != 1:
            A = np.linalg.matrix_power(A,c)
        if d != 1:
            B = np.linalg.matrix_power(B,d)

        out = A@B
  
    print("\n")
    print(out)

# Punto 2

## a)
Sean $A,B, C$ las siguientes matrices:
     
$$ A = \left[ \begin{array}{cc}
    0.1 & 2 \\
    2 & 0.1
\end{array} \right] \qquad
B = \left[ \begin{array}{ccc}
    1 & 2 & 3 \\
    4 & 5 & 4
\end{array} \right] \qquad C = \left[ \begin{array}{cc}
    \frac{5}{3} & \frac{2}{3}  \\
    \frac{2}{3} & \frac{5}{3}
\end{array} \right]  $$

Se muestran los resultados de los siguientes puntos en consola a partir de la función $\texttt{fun1}()$

1. $A*B^T$
2. $A^2*B$
3. $B*C^3$
4. $B^T*C^4$

In [3]:
A = np.array([[0.1 , 2],[2, 0.1]])
B = np.array([[1,2,3],[4,5,6]])
C = np.array([[5/3, 2/3],[2/3, 5/3]])

print('\n 1)  A*B^T')
fun1(A,np.transpose(B))

print('\n 2) A^2*B')
fun1(A,B,2)

print('\n 3) B*C^3')
fun1(B,C,1,3)

print('\n 4) B^T*C^4')
fun1(np.transpose(B),C,1,4)



 1)  A*B^T


Error: El primer arreglo tiene menos columnas que el segundo filas

 2) A^2*B


[[ 5.61 10.02 14.43]
 [16.44 20.85 25.26]]

 3) B*C^3


Error: El primer arreglo tiene mas columnas que el segundo filas

 4) B^T*C^4


[[ 72.60493827  75.60493827]
 [102.24691358 105.24691358]
 [131.88888889 134.88888889]]


## b)
A continuación una sección de código, que cumple los requerimientos: solicita los parámetros $c,d$ de $\texttt{fun1}$ y seguidamente la corre con las matrices $A$ y $B$ creadas anteriormente. Envia mensaje de error cuando el usuario introduce un número que no genera error en la función $\texttt{matrix_power}$ de la libreria $\texttt{np.linalg}$ (número no entero) o cuando introduce un caracter no númerico.



In [4]:
# Se compacta proceso en uno solo.
for i in range(1):
    
    # Manejo del primer número
    c = input('Primer número: ')
    try:
        c = int(c)
    except ValueError:
        print('Error, no se introdujo un número válido')
        break

    # Manejo del primer número
    d = input('Segundo número: ')
    try:
        d = int(d)
    except ValueError:
        print('Error, no se introdujo un número válido')
        break

    fun1(A,C,c,d)



[[3283.16407667 3307.92506667]
 [3307.92506667 3283.16407667]]


## Errores

In [5]:
print('\n A')
print(A)

print('\n A**2')
print(A**2)

print('\n A^2')
print(np.linalg.matrix_power(A,2))


 A
[[0.1 2. ]
 [2.  0.1]]

 A**2
[[0.01 4.  ]
 [4.   0.01]]

 A^2
[[4.01 0.4 ]
 [0.4  4.01]]
