# Introduction to Python I

In [1]:
import numpy as np

# Part 1 - Matrix multiplication

Define a function $f$ that satisfies the following requirements:

a) Returns the matrix multiplication of two parameter matrices.

b) Checks for errors of dimensionality and allows to raise the matrices to a certain power.

---

We based our solution on the [numpy matrix vector multiplication](https://stackoverflow.com/questions/21562986/numpy-matrix-vector-multiplication) question, and the documentation on [How to raise a numpy array to a power?](https://stackoverflow.com/questions/5018552/how-to-raise-a-numpy-array-to-a-power-corresponding-to-repeated-matrix-multipl)

The function $f$ that satisfies the requirements of a) and b) is $\texttt{fun1(A,B,c,d)}$.

This function handles two types of errors. The first one occurs when A has more columns than B has rows, and the second one occurs when the opposite happens.

In [2]:
def fun1(A, B, c=1, d=1):
    
    # Transform objects into numpy arrays
    A = np.array(A)
    B = np.array(B)
    
    # First type of dimension error
    if A.shape[1] > B.shape[0]:
        out = 'Error: The first array has more columns than the second has rows'
    # Second type of dimension error
    elif A.shape[1] < B.shape[0]:
        out = 'Error: The first array has fewer columns than the second has rows'
    # Perform the operation
    else:
        # linalg.matrix_power generates an error for non-square matrices
        # regardless of whether the exponent is 1
        # Handle the error
        if c != 1:
            A = np.linalg.matrix_power(A, c)
        if d != 1:
            B = np.linalg.matrix_power(B, d)

        out = A @ B
  
    print("\n")
    print(out)

# Part 2 - Testing Functions

## a)
Let $A$, $B$, and $C$ be the following matrices:
     
$$ A = \left[ \begin{array}{cc}
    0.1 & 2 \\
    2 & 0.1
\end{array} \right] \qquad
B = \left[ \begin{array}{ccc}
    1 & 2 & 3 \\
    4 & 5 & 4
\end{array} \right] \qquad C = \left[ \begin{array}{cc}
    \frac{5}{3} & \frac{2}{3}  \\
    \frac{2}{3} & \frac{5}{3}
\end{array} \right]  $$

The results of the following operations are displayed in the console using the function $\texttt{fun1}()$:

1. $A*B^T$
2. $A^2*B$
3. $B*C^3$
4. $B^T*C^4$


In [3]:
A = np.array([[0.1 , 2],[2, 0.1]])
B = np.array([[1,2,3],[4,5,6]])
C = np.array([[5/3, 2/3],[2/3, 5/3]])

print('\n 1)  A*B^T')
fun1(A,np.transpose(B))

print('\n 2) A^2*B')
fun1(A,B,2)

print('\n 3) B*C^3')
fun1(B,C,1,3)

print('\n 4) B^T*C^4')
fun1(np.transpose(B),C,1,4)



 1)  A*B^T


Error: The first array has fewer columns than the second has rows

 2) A^2*B


[[ 5.61 10.02 14.43]
 [16.44 20.85 25.26]]

 3) B*C^3


Error: The first array has more columns than the second has rows

 4) B^T*C^4


[[ 72.60493827  75.60493827]
 [102.24691358 105.24691358]
 [131.88888889 134.88888889]]


## b)
Below is a code snippet that tries error cases for the defined function: it prompts the parameters $c$ and $d$ for $\texttt{fun1}$ and then runs it with the matrices $A$ and $B$ created earlier. It sends an error message when the user inputs a number that doesn't cause an error in the $\texttt{matrix\_power}$ function of the $\texttt{np.linalg}$ library (non-integer number) or when a non-numeric character is entered.


In [4]:
# The process is compacted into one.
for i in range(1):
    
    # Handling the first number
    c = input('First number: ')
    try:
        c = int(c)
    except ValueError:
        print('Error, an invalid number was entered')
        break

    # Handling the second number
    d = input('Second number: ')
    try:
        d = int(d)
    except ValueError:
        print('Error, an invalid number was entered')
        break

    fun1(A, C, c, d)




[[4.76666667 6.66666667]
 [6.66666667 4.76666667]]


## Errors

In [5]:
print('\n A')
print(A)

print('\n A**2')
print(A**2)

print('\n A^2')
print(np.linalg.matrix_power(A,2))


 A
[[0.1 2. ]
 [2.  0.1]]

 A**2
[[0.01 4.  ]
 [4.   0.01]]

 A^2
[[4.01 0.4 ]
 [0.4  4.01]]
