In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.linalg import sqrtm

In [2]:
Cy = np.array([[25, 1], [1, 9]])
Cx = np.array([[1, 0.1], [0.1, 2]])

In [3]:
# Vectores propios de Cx
valsCx, vectsCx = np.linalg.eig(Cx) # Ya salen normalizados

# Se crea matriz Lambda con los valores propios
LambdaCx = np.array([[valsCx[0], 0], [0, valsCx[1]]])

# Se crea la matriz G, con G = Cx^1/2
G = np.matmul(np.matmul(vectsCx, np.sqrt(LambdaCx)), vectsCx.T)
print(f'Matriz G calculada con la fórmula: \n {G}')
G2 = sqrtm(Cx)
print(f'\nMatriz G calculada con función sqrtm: \n {G2}')

Matriz G calculada con la fórmula: 
 [[0.99914072 0.04144654]
 [0.04144654 1.41360609]]

Matriz G calculada con función sqrtm: 
 [[0.99914072 0.04144654]
 [0.04144654 1.41360609]]


In [4]:
# Vectores propios de Cy
valsCy, vectsCy = np.linalg.eig(Cy) # Ya salen normalizados

# Se crea matriz Lambda con los valores propios
LambdaCy = np.array([[valsCy[0], 0], [0, valsCy[1]]])
# Se crea matriz Lambda con 1/valores propios
LambdaCy = np.array([[1/valsCy[0], 0], [0, 1/valsCy[1]]])

# Se crea la matriz H, con H = Cx^-1/2
H = np.matmul(np.matmul(vectsCy, np.sqrt(LambdaCy)), vectsCy.T)
print(f'Matriz H calculada con la fórmula = \n {H}')
H2 = sqrtm(Cy)
print(f'\nMatriz H calculada con función sqrtm = \n {H2}')

Matriz H calculada con la fórmula = 
 [[ 0.20027168 -0.00835627]
 [-0.00835627  0.33397203]]

Matriz H calculada con función sqrtm = 
 [[4.99843562 0.12506523]
 [0.12506523 2.99739198]]


In [5]:
A = np.matmul(G, H)
print(f'Matriz A = \n {A}')

print(f'\nSe confirma que la matrix Cx está dada por ACyA^T= \n {np.matmul(np.matmul(A, Cy), A.T)}')

Matriz A = 
 [[ 0.19975325  0.00549289]
 [-0.00351191  0.47175856]]

Se confirma que la matrix Cx está dada por ACyA^T= 
 [[1.  0.1]
 [0.1 2. ]]
