In [3]:
import numpy as np
import matplotlib.pyplot as plt

A = np.array([[2,3],[6,7]])
B = np.array([[1,3],[0,9]])

print(A*B)
print(np.matmul(B,A))
print(np.dot(B,A))

[[ 2  9]
 [ 0 63]]
[[20 24]
 [54 63]]
[[20 24]
 [54 63]]
